version: "2"
services:
  application:
    image: ${IMAGE_NAME}
    container_name: ThreatLens
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID = ${AWS_ACCESS_KEYID}
      - AWS_SECRET_ACCESS_KEY = ${AWS_ACCESS_KEY}
      - AWS_DEFAULT_REGION = ${AWS_REGION}
      - MONGO_DB_URL = ${MONGODB_URL}
      - BUCKET_NAME = ${BUCKET_NAME}